version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
    timeout: 500
  ApplicationStart:
    - location: scripts/npm-start.sh
    timeout: 3600
